### ISSUE TITLE
Uno R4 Minima

### ISSUE THREAD

**Issue by nissim1** [mrjimenez/JTAG#14]
Hi,

I tried to Verify the example JTAGTest.ino on Uno R4 Minima and got this error:
![r4](https://github.com/mrjimenez/JTAG/assets/20010138/20515901-281f-41b6-90aa-5fdae5053644)

thanks.

**Comment by mrjimenez** [comment]
What is the version of the IDE that you are using to compile it? I will try to reproduce the problem here.

**Comment by nissim1** [comment]
<img width="193" alt="image" src="https://github.com/mrjimenez/JTAG/assets/20010138/ce523561-a345-4adc-af3c-36e785c401ed">

**Comment by mrjimenez** [comment]
Can you check if #15 fixes the problem for you?

**Comment by nissim1** [comment]
Do you mean?
![15](https://github.com/mrjimenez/JTAG/assets/20010138/5f0da1c0-cc79-461d-947f-22d2d02a2e04)

**Comment by mrjimenez** [comment]
No, I meant the pull request. But let's do the following, I will release 1.0.16, so that you can test it, ok? Give me one day.

**Comment by mrjimenez** [comment]
Hi @nissim1 , any news? Version 1.0.17 is already published on the Arduino library manager.

**Comment by nissim1** [comment]
thank you!
with version 1.0.17 the problem is fixed.
